name: Deploy NextJS App in AWS EC2

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: jovemhero/todo:latest
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker stop todo || true
            docker rm todo || true
            docker image rm ${{ secrets.DOCKER_USERNAME }}/todo:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo:latest
            docker run -d --name todo -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/todo:latest
